# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Mocking
tagline:          'Test Doubles for Fun and Profit'
description:      'Going deeper with Test Driven Development using test doubles to test complex interactions.'
url:              https://lazarusid.github.io/
baseurl:          /embedded-life/

author:
  name:           'Clay Dowling'
  url:            http://claydowling.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/LazarusID/embedded-life
